#!/usr/bin/env python3
"""Sync docs/error-codes.md from CustomError definitions in the Django project.

docs/error-codes.md is treated as a generated artifact. Developers edit
CustomError subclasses; this script regenerates the registry and detects
inconsistencies (duplicates, out-of-range codes, cross-file overlaps).

Usage:
    python scripts/sync_error_docs.py --check   # exit 1 if diff or violations
    python scripts/sync_error_docs.py --diff    # show diff only
    python scripts/sync_error_docs.py --write   # overwrite docs/error-codes.md

Configuration:
    scripts/error_domains.yaml — maps 100-unit prefix → human-readable domain name.
    Seeded from the existing docs/error-codes.md on first run.
"""
from __future__ import annotations

import argparse
import ast
import difflib
import re
import sys
from collections import defaultdict
from dataclasses import dataclass, field
from pathlib import Path
from typing import Iterable

try:
    import yaml  # type: ignore
except ImportError:
    yaml = None  # fall back to tiny inline parser below

REPO_ROOT = Path(__file__).resolve().parent.parent
DJANGO_ROOT = REPO_ROOT / "django"
DOCS_PATH = REPO_ROOT / "docs" / "error-codes.md"
DOMAINS_YAML = Path(__file__).resolve().parent / "error_domains.yaml"

CUSTOM_ERROR_BASES = {"CustomError"}  # extend if project uses more base names
AUTO_HEADER = (
    "<!-- AUTO-GENERATED by scripts/sync_error_docs.py. "
    "Edit CustomError definitions instead. -->\n"
)


@dataclass
class ErrorDef:
    code: int
    message: str
    class_name: str
    file: Path  # relative to REPO_ROOT


@dataclass
class SubGroup:
    prefix: int  # e.g. 20000, 20100
    start: int
    end: int
    files: set[Path] = field(default_factory=set)
    name: str = ""


@dataclass
class Violation:
    kind: str  # NOT_5_DIGIT | DUPLICATE | RANGE_OVERLAP | UNKNOWN_DOMAIN
    message: str


# ---------------------------------------------------------------------------
# AST collection
# ---------------------------------------------------------------------------

def _extends_custom_error(node: ast.ClassDef) -> bool:
    for base in node.bases:
        name = _base_name(base)
        if name and name in CUSTOM_ERROR_BASES:
            return True
    return False


def _base_name(node: ast.expr) -> str | None:
    if isinstance(node, ast.Name):
        return node.id
    if isinstance(node, ast.Attribute):
        return node.attr
    return None


def _extract_class_level(node: ast.ClassDef, attr: str) -> ast.expr | None:
    for stmt in node.body:
        if isinstance(stmt, ast.Assign):
            for target in stmt.targets:
                if isinstance(target, ast.Name) and target.id == attr:
                    return stmt.value
        elif isinstance(stmt, ast.AnnAssign):
            if isinstance(stmt.target, ast.Name) and stmt.target.id == attr and stmt.value is not None:
                return stmt.value
    return None


def _literal(node: ast.expr | None):
    if node is None:
        return None
    try:
        return ast.literal_eval(node)
    except (ValueError, SyntaxError):
        return None


def collect(root: Path) -> list[ErrorDef]:
    defs: list[ErrorDef] = []
    for py in root.rglob("exceptions/**/*.py"):
        if py.name == "__init__.py":
            continue
        try:
            tree = ast.parse(py.read_text(encoding="utf-8"), filename=str(py))
        except SyntaxError:
            continue
        for node in ast.walk(tree):
            if not isinstance(node, ast.ClassDef):
                continue
            if not _extends_custom_error(node):
                continue
            code_val = _literal(_extract_class_level(node, "code"))
            msg_val = _literal(_extract_class_level(node, "message"))
            if code_val is None:
                # also try `status_code`
                code_val = _literal(_extract_class_level(node, "status_code"))
            if code_val is None or not isinstance(code_val, int):
                continue
            rel = py.relative_to(REPO_ROOT)
            defs.append(
                ErrorDef(
                    code=code_val,
                    message=str(msg_val) if msg_val is not None else "",
                    class_name=node.name,
                    file=rel,
                )
            )
    # also scan bare exceptions.py files
    for py in root.rglob("exceptions.py"):
        try:
            tree = ast.parse(py.read_text(encoding="utf-8"), filename=str(py))
        except SyntaxError:
            continue
        for node in ast.walk(tree):
            if not isinstance(node, ast.ClassDef) or not _extends_custom_error(node):
                continue
            code_val = _literal(_extract_class_level(node, "code")) or _literal(
                _extract_class_level(node, "status_code")
            )
            if not isinstance(code_val, int):
                continue
            msg_val = _literal(_extract_class_level(node, "message"))
            rel = py.relative_to(REPO_ROOT)
            defs.append(
                ErrorDef(
                    code=code_val,
                    message=str(msg_val) if msg_val is not None else "",
                    class_name=node.name,
                    file=rel,
                )
            )
    return defs


# ---------------------------------------------------------------------------
# Grouping & violations
# ---------------------------------------------------------------------------

def group_subgroups(defs: list[ErrorDef]) -> list[SubGroup]:
    """Group by 100-unit prefix. Each prefix is a distinct domain row."""
    buckets: dict[int, list[ErrorDef]] = defaultdict(list)
    for d in defs:
        buckets[(d.code // 100) * 100].append(d)
    groups: list[SubGroup] = []
    for prefix, items in sorted(buckets.items()):
        groups.append(
            SubGroup(
                prefix=prefix,
                start=prefix,
                end=prefix + 99,
                files={i.file for i in items},
            )
        )
    return groups


def detect_violations(defs: list[ErrorDef], groups: list[SubGroup]) -> list[Violation]:
    v: list[Violation] = []
    # 5-digit check
    for d in defs:
        if not (10000 <= d.code <= 99999):
            v.append(
                Violation(
                    "NOT_5_DIGIT",
                    f"{d.file}::{d.class_name} has code={d.code} (must be 5 digits)",
                )
            )
    # duplicates
    by_code: dict[int, list[ErrorDef]] = defaultdict(list)
    for d in defs:
        by_code[d.code].append(d)
    for code, items in by_code.items():
        if len(items) > 1:
            locs = ", ".join(f"{i.file}::{i.class_name}" for i in items)
            v.append(Violation("DUPLICATE", f"code {code} defined in: {locs}"))
    # cross-prefix file pollution: same prefix claimed by too-disparate files is fine,
    # but if a single prefix spans files, we flag it as RANGE_OVERLAP for review.
    for g in groups:
        if len(g.files) > 1:
            files = ", ".join(sorted(str(f) for f in g.files))
            v.append(
                Violation(
                    "RANGE_OVERLAP",
                    f"prefix {g.prefix}~{g.end} spans multiple files: {files}",
                )
            )
    return v


# ---------------------------------------------------------------------------
# Domain names (yaml)
# ---------------------------------------------------------------------------

def load_domains_map() -> dict[int, str]:
    if not DOMAINS_YAML.exists():
        return {}
    text = DOMAINS_YAML.read_text(encoding="utf-8")
    if yaml:
        data = yaml.safe_load(text) or {}
    else:
        data = _tiny_yaml_parse(text)
    # keys may be int or str; normalize
    return {int(k): str(v) for k, v in data.items()}


def save_domains_map(mapping: dict[int, str]) -> None:
    lines = ["# prefix (5-digit start) -> human-readable domain name\n"]
    for prefix in sorted(mapping):
        lines.append(f"{prefix}: {mapping[prefix]!r}\n")
    DOMAINS_YAML.write_text("".join(lines), encoding="utf-8")


def _tiny_yaml_parse(text: str) -> dict:
    """Minimal `key: value` parser so script works without PyYAML installed."""
    out: dict = {}
    for line in text.splitlines():
        line = line.split("#", 1)[0].strip()
        if not line or ":" not in line:
            continue
        k, _, v = line.partition(":")
        v = v.strip().strip("'\"")
        out[k.strip()] = v
    return out


RANGE_ROW_RE = re.compile(
    r"^\|\s*`(\d{5})~(\d{5})`\s*\|\s*([^|]+?)\s*\|\s*([^|]+)\s*\|"
)


def seed_domains_from_existing_docs(existing: str) -> dict[int, str]:
    """Parse the existing docs table to extract prefix → domain name, one-time."""
    mapping: dict[int, str] = {}
    for line in existing.splitlines():
        m = RANGE_ROW_RE.match(line)
        if not m:
            continue
        start = int(m.group(1))
        name = m.group(3).strip()
        mapping[(start // 100) * 100] = name
    return mapping


# ---------------------------------------------------------------------------
# Rendering
# ---------------------------------------------------------------------------

def render(groups: list[SubGroup], domains: dict[int, str]) -> str:
    lines: list[str] = []
    lines.append(AUTO_HEADER)
    lines.append("# Error Code Registry\n\n")
    lines.append(
        "The frontend checks the 5-digit `error_code` first before falling back to the HTTP status code.\n\n"
    )
    lines.append("## Code Ranges\n\n")
    lines.append("| Range | Domain | Exception file |\n")
    lines.append("|-------|--------|----------------|\n")
    for g in groups:
        name = domains.get(g.prefix) or f"Unknown ({g.prefix // 100:03d}xx)"
        files = ", ".join(f"`{p}`" for p in sorted(g.files, key=str))
        lines.append(f"| `{g.start:05d}~{g.end:05d}` | {name} | {files} |\n")
    lines.append("\n## Adding a new error code\n\n")
    lines.append("1. Define a new `CustomError` subclass in the appropriate exception file\n")
    lines.append("2. Assign `code` using the next available number in the domain's prefix range\n")
    lines.append("3. If it starts a new prefix, add the domain name to `scripts/error_domains.yaml`\n")
    lines.append("4. Run `python scripts/sync_error_docs.py --write` to regenerate this file\n")
    return "".join(lines)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def _unified_diff(old: str, new: str, path: Path) -> str:
    return "".join(
        difflib.unified_diff(
            old.splitlines(keepends=True),
            new.splitlines(keepends=True),
            fromfile=str(path),
            tofile=str(path) + " (generated)",
        )
    )


def main() -> int:
    ap = argparse.ArgumentParser()
    g = ap.add_mutually_exclusive_group(required=True)
    g.add_argument("--check", action="store_true", help="exit 1 on diff or violations")
    g.add_argument("--diff", action="store_true", help="print diff only")
    g.add_argument("--write", action="store_true", help="write docs/error-codes.md")
    args = ap.parse_args()

    if not DJANGO_ROOT.exists():
        print(f"[error] django/ not found at {DJANGO_ROOT}", file=sys.stderr)
        return 2

    defs = collect(DJANGO_ROOT)
    groups = group_subgroups(defs)
    violations = detect_violations(defs, groups)

    existing = DOCS_PATH.read_text(encoding="utf-8") if DOCS_PATH.exists() else ""

    # seed domains yaml on first run
    domains = load_domains_map()
    if not domains and existing:
        domains = seed_domains_from_existing_docs(existing)
        save_domains_map(domains)
        print(f"[info] seeded {DOMAINS_YAML} from existing docs ({len(domains)} entries)", file=sys.stderr)

    # flag unknown domains
    for g_ in groups:
        if g_.prefix not in domains:
            violations.append(
                Violation(
                    "UNKNOWN_DOMAIN",
                    f"prefix {g_.prefix} has no name in {DOMAINS_YAML.name} — will render as 'Unknown'",
                )
            )

    rendered = render(groups, domains)
    diff = _unified_diff(existing, rendered, DOCS_PATH)

    hard_violations = [v for v in violations if v.kind != "UNKNOWN_DOMAIN"]

    if args.write:
        DOCS_PATH.parent.mkdir(parents=True, exist_ok=True)
        DOCS_PATH.write_text(rendered, encoding="utf-8")
        print(f"[ok] wrote {DOCS_PATH}", file=sys.stderr)
        _print_violations(violations)
        return 0

    if args.diff:
        if diff:
            sys.stdout.write(diff)
        _print_violations(violations)
        return 0

    # --check
    has_diff = bool(diff)
    if has_diff:
        sys.stdout.write(diff)
    _print_violations(violations)
    if has_diff or hard_violations:
        return 1
    print("[ok] error code registry is consistent", file=sys.stderr)
    return 0


def _print_violations(vs: Iterable[Violation]) -> None:
    vs = list(vs)
    if not vs:
        return
    print("\n--- violations ---", file=sys.stderr)
    for v in vs:
        print(f"  [{v.kind}] {v.message}", file=sys.stderr)


if __name__ == "__main__":
    raise SystemExit(main())
